### ISSUE TITLE
Comparison to mothur's implementation of SparCC

### ISSUE THREAD

**Issue by pschloss** [scwatts/alt_impl_cmp#1]
Thanks for including `mothur`'s implementation of SparCC in your all's analysis and preprint. To be honest, I'm surprised you got it to work on any of the datasets given the fact that there was a mysterious bug that is in v. 1.39 and 1.40. The bug should have prevented you from running the command at all. Regardless, we have removed the offending line of code. This bug fix will be released early next week as part of v.1.40.3 (you can find it on the [sparcc branch](https://github.com/mothur/mothur/tree/sparcc)).

I have repeated your all's analyses using `fake_data.txt`, `otu_table_subset_200_50.tsv`, and `otu_table_subset_500_1000.tsv`.

With `fake_data.txt`, I get the following correlations...

```
             mothur    sparcc spieceasi  fastspar
mothur    1.0000000 0.9636594 0.9659869 0.9644695
sparcc    0.9636594 1.0000000 0.9796533 0.9771492
spieceasi 0.9659869 0.9796533 1.0000000 0.9783019
fastspar  0.9644695 0.9771492 0.9783019 1.0000000
```

With `otu_table_subset_200_50.tsv`, I get the following correlations...

```
             mothur    sparcc spieceasi  fastspar
mothur    1.0000000 0.7957353 0.7979573 0.7953136
sparcc    0.7957353 1.0000000 0.8766496 0.8769998
spieceasi 0.7979573 0.8766496 1.0000000 0.8759344
fastspar  0.7953136 0.8769998 0.8759344 1.0000000
```

With `otu_table_subset_500_1000.tsv`, I get the following correlations...

```
             mothur    sparcc spieceasi  fastspar
mothur    1.0000000 0.9263466 0.9260754 0.9261140
sparcc    0.9263466 1.0000000 0.9290809 0.9290413
spieceasi 0.9260754 0.9290809 1.0000000 0.9291165
fastspar  0.9261140 0.9290413 0.9291165 1.0000000
```

When I timed the `mothur` version with the 500/1000 dataset it took about 5 minutes to run (on my MacBook Pro) whereas the `fastspar` took about a minute to run (on linux). It also seemed like `spieceasi` and `sparcc` took about the same amount of time to run.

We also had a bug in our threading that has now been fixed. We do threading differently - we thread across the randomizations for the p-value calculations whereas you all do it within each randomization (I think).

Regardless, I think the fixed code shows that we get pretty comparable results as the other methods.

**Comment by scwatts** [comment]
Hi Pat, thank you for posting the update. We've run the comparison again ourselves using mothur v1.40.3 with the three datasets (results using `otu_table_subset_500_1000.tsv` as input shown below). The mothur SparCC implementation performs well in terms of run time and memory usage. The data from the analysis largely match what you've reported above - the output of each implementation has a high degree of correlation though we observed some differences between the distributions.

![correlation_plot](https://user-images.githubusercontent.com/463926/41384759-01c3ecca-6fbb-11e8-9c5c-1ae412db8ce1.png)

We also found that under some circumstances `SpiecEasi` will have a similar run-time as `SparCC`. This is usually a result of thread oversubscription (due to how threads are handled in the underlying libraries) or using a less performant BLAS library.  Under optimal conditions `SpiecEasi` is observed to have an improvement over `SparCC`.

![profile_time](https://user-images.githubusercontent.com/463926/41384761-02202f1c-6fbb-11e8-9700-f24f8870ca23.png)
![profile_memory](https://user-images.githubusercontent.com/463926/41384760-01f521aa-6fbb-11e8-814b-321746996588.png)
